### PR TITLE
deepin-keyring 2023.09.26

### PR DESCRIPTION
**Pull request by UTsweetyfish**
- fix: updates from repo
  Tracking deepin-keyring_2021.06.07-1.dsc
- fix: Depends on gpgv instead of gnupg
  ... make deepin-keyring bootstrapable.
  Switch to 3.0 (native)
  Bump version 2023.09.26.

### CODE REVIEW

**Review by Zeno-sole — APPROVED** [review]

**Comment by Zeno-sole** [comment]
add review @BLumia

**Review by BLumia — APPROVED** [review]

**Pull request merged**
